### ISSUE TITLE
New Stat for Mission Days attended

### ISSUE THREAD

**Issue by johnluetke** [BlueHerons/StatTracker#125]
`Mission Day(s) Attended`

![720x1280 png 1c00933253a8410286c68b97bd42d81c](https://cloud.githubusercontent.com/assets/348843/13716590/f2e26920-e790-11e5-8ff6-adb51a4909d7.jpg)

**Comment by johnluetke** [comment]
Added the stat to the live Db so at least it is present on he manual entry screen and leaderboards

**Comment by Fragger** [comment]
I'm assuming this just doesn't show when it's 0?

**Comment by Fragger** [comment]
Fixed in #126
