### ISSUE TITLE
Initial Stat Submission

### ISSUE THREAD

**Issue by johnluetke** [BlueHerons/StatTracker#127]
Functionality is **severely** limited for new users who have not submitted thier stats at least once. They cant even generate a token to use with the app.

Perhaps create an initial stat submission of all 0's?

**Comment by Fragger** [comment]
Perhaps ask for their start date when no submissions exist for a user and
make an all 0 entry there.

**Comment by johnluetke** [comment]
The only benefit I could see to that is provided an assumption-heavy view into stat increase per day. Most of the data queries also limit to the past 30 days, so it could be moot.

**Comment by andschwa** [comment]
Ran into this as well, had to submit a blank entry before being able to generate the token.
