### ISSUE TITLE
Sharing error: image not found

### ISSUE THREAD

**Issue by andschwa** [BlueHerons/StatTracker#130]
Using v1.100 of Ingress, I can share the screenshot of the agent page to the stats tracker app, but then see this screen:

![screenshot_20160526-173932](https://cloud.githubusercontent.com/assets/2226434/15594581/c8bbe7ea-236b-11e6-923e-5227626f52a1.png)

Using a Nexus 6P and current store version of the StatTracker app.

**Comment by Fragger** [comment]
This isn't an issue directly with stat tracker but with stat tracker app.  See https://github.com/BlueHerons/StatTrackerApp/issues/3
