### ISSUE TITLE
Allow user to override a stats submission to go on the preceding day.

### ISSUE THREAD

**Issue by Meowse** [BlueHerons/StatTracker#25]
Default the "target day" to the current day (rolls over at midnight), but make it a two-element drop-down with the other option being the preceding day, so that each user can flexibly decide which day to record each checkpoint on.

If the "target day" dropdown is right next to the "Submit your stats", it will be easy for the user both to validate that the stats are being applied to the correct day, and to fix it if not.

**Comment by johnluetke** [comment]
Fixed in #51
