### ISSUE TITLE
New StatTracker users have incorrect leaderboard standings

### ISSUE THREAD

**Issue by Meowse** [BlueHerons/StatTracker#30]
When an agent first starts using StatTracker, ask them for the date that they started playing Ingress.  Create an "all zeros" stats entry on that date.  This will avoid the problem of anomalously large weekly leaderboard results when a new agent joints StatTracker.

**Comment by johnluetke** [comment]
This also affects users who have not submitted in a long time.

**Comment by phthoruth** [comment]
Also affects users that dont submit stats on Sunday.
Too lesser extent affects users whos stats on Sunday are different than rest of week.

**Comment by johnluetke** [comment]
I've tried to mitigate the no-Sunday submission with predictions (see https://github.com/BlueHerons/StatTracker/wiki/Using-Stat-Tracker#but-what-happens-if-an-agent-does-not-submit-on-a-sunday)

It works well enough, but obviously isn't perfect.

**Comment by johnluetke** [comment]
Closing in favor of #127
