### ISSUE TITLE
Request: commas in number fields 

### ISSUE THREAD

**Issue by mkhamer** [BlueHerons/StatTracker#40]
If possible, please add commas in the number fields, like the Ingress stats themselves display. This will make it easier to spot errors, especially in manual entry.

**Comment by johnluetke** [comment]
I'm doing some research into this, and I was able to get formatting comma's to display with all the numbers, except those on the "submit stats" screen. Is this where you intended them to be introduced?

**Comment by mkhamer** [comment]
Yes, it was. Although having them anywhere would be an improvement.

**Comment by johnluetke** [comment]
Ok, I can get them into the Dashboard and Leaderboards no problem, but would have to do some overhaul on the Stats page
