### ISSUE TITLE
Add support for "Recruiter" badge.

### ISSUE THREAD

**Issue by johnluetke** [BlueHerons/StatTracker#41]
Stat name: Agents Successfully Recruited
Heading: Mentoring

Its placed at the very bottom of the profile screen.

**Comment by johnluetke** [comment]
Badge images: http://imgur.com/vtxUoOT

**Comment by Fragger** [comment]
Noooo delete it :p

**Comment by johnluetke** [comment]
Haha, if it didn't effect leveling, I would have continued to ignore it

**Comment by johnluetke** [comment]
That image sucked in terms of resolution. Since This badge is equivalent to "Seer" in that the agent doesn't directly control its value, I wont update the badge swatch as this time.
