### ISSUE TITLE
Error upon Screenshot Upload

### ISSUE THREAD

**Issue by thenafun** [BlueHerons/StatTracker#52]
Today, when I try to upload a screenshot I get "an error occurred while processing your screenshot"

![screenshot_2015-02-17-12-18-40](https://cloud.githubusercontent.com/assets/11050319/6236385/439edb7e-b69f-11e4-968b-d37d17037482.png)

**Comment by johnluetke** [comment]
UPLOAD_DIR is not writeable. Their should be a sanity check for this when the site first loads.
