### ISSUE TITLE
top40 style leaderboard 

### ISSUE THREAD

**Issue by phthoruth** [BlueHerons/StatTracker#62]
For the guardian stats, I copied the stats a few days ago
All-time
Rank	Agent	Amount	Updated
1	KernelTruth	537	6 days ago
2	TrggrHppyNana	279	18 days ago
3	DashMorlock	262	Today
4	magnusansky	251	Yesterday
5	sockhopper	251	7 days ago
6	Demothesses	235	3 days ago
7	Darkonus	228	2 days ago
8	wreckSTAR	192	2 days ago
9	sAMAccountName	192	Yesterday
10	chuntr	178	15 days ago
11	gillihan	177	2 days ago
12	jtweetyone	177	Today
13	BobTerwilliger	175	26 days ago
14	zpo	175	4 days ago
15	northumbrian	172	Yesterday
16	AoD7	163	3 days ago
17	TheSuperman	161	Yesterday
18	PapabearSmurf	160	Today
19	Banjo1	158	7 days ago
20	swiftness	156	3 days ago
21	opsan	156	24 days ago
22	Camicat	154	21 days ago
23	AbleCain	154	Today
24	phthoruth	154	Today
25	sahararomeo	153	Today
26	ScruffyNrdHrdr	152	7 days ago
27	AoD42	150	2 days ago
28	Ba1r0g	149	16 days ago
29	PaidtoDecimate	148	Yesterday
30	BoatAnchor	148	6 days ago
31	R0cknu	148	Yesterday

and then again today
All-time
Rank	Agent	Amount	Updated
1	KernelTruth	537	8 days ago
2	TrggrHppyNana	279	20 days ago
3	DashMorlock	262	2 days ago
4	sockhopper	258	2 days ago
5	magnusansky	251	3 days ago
6	Demothesses	235	5 days ago
7	Darkonus	228	4 days ago
8	wreckSTAR	195	Today
9	sAMAccountName	192	3 days ago
10	chuntr	178	17 days ago
11	gillihan	177	4 days ago
12	jtweetyone	177	2 days ago
13	BobTerwilliger	175	28 days ago
14	zpo	175	2 days ago
15	northumbrian	172	Today
16	AoD7	163	5 days ago
17	TheSuperman	161	Today
18	PapabearSmurf	160	Today
19	Banjo1	158	9 days ago
20	swiftness	156	5 days ago
21	opsan	156	26 days ago
22	phthoruth	156	Today
23	sahararomeo	154	Yesterday
24	Camicat	154	23 days ago
25	AbleCain	154	Today
26	ScruffyNrdHrdr	152	9 days ago
27	AoD42	150	Yesterday
28	Ba1r0g	149	18 days ago
29	PaidtoDecimate	148	Yesterday
30	BoatAnchor	148	Yesterday
31	R0cknu	148	Yesterday

I moved up the ranking from #24 to #22 and can figure out which agents have ticking guardians.
It occurred to me statstracker could figure this out for me, by comparing stats to a week ago, and show changes, much like a top 40 chart.

Here is an actual top 40 chart
http://www.at40.com/top-40/chart/35511

They show this week vs last week, and if you are moving up, down or the same.

**Comment by johnluetke** [comment]
I think this is a terrible idea for guardians, but good for other stats
