### ISSUE TITLE
OCR Stat Header tolerance

### ISSUE THREAD

**Issue by Fragger** [BlueHerons/StatTracker#70]
OCR was failing in one case where the Discovery header was being returned from the image as "Discovery _" this fails to be matched by `'/^\s*Discovery\s*$/sxmi'`.  Maybe it would be good to be slightly more forgiving in the matching code and use something like: `'/^\s*Discovery/sxmi'` to not care about matching the whole line to the end.  Thoughts?

**Comment by johnluetke** [comment]
Will this still apply after your OCR re-factoring?

**Comment by Fragger** [comment]
It will be one of the commits that is part of the re-factoring.  Using `strpos($haystack, $needle) !== false` right now for the simple matching lines.
