### ISSUE TITLE
Leaderboard AP breakdown - liberate 625 AP

### ISSUE THREAD

**Issue by phthoruth** [BlueHerons/StatTracker#87]
The AP breakdown uses 500 AP for 'Portal Captuerd', and puts the other 125 AP under 'Resonators Deployed'

Resonators Deployed is using 65 AP for portals, because it may be an upgrade, but a liberate is guaranteed to be an open deploy for 125 AP, so the formula compensates for liberates like this:
=(deploy-liberate)*65+(liberate*(125-65))

Since Liberates are guaranteed 625 AP and an important part of your AP, and deploys are ambiguous and may or may not be a big factor, I'd like to see the full 625 AP credited to liberates.

**Comment by johnluetke** [comment]
I think representing a capture as 625 AP instead of 500 AP for the capture, and 125 AP for the single deploy would be misleading. 

The COMM log of the game calls out each action separately, and the stats for capture and deploys increment separately.

Thoughts?

**Comment by phthoruth** [comment]
When you capture a portal, you get 625 AP.
Thats the biggest part of my AP, and I think its misleading to show some of
it under deploy.
It unabiguous, unlike deploys/upgrade.  I'd like to know for sure, how much
AP I'm getting from liberate.

**Comment by johnluetke** [comment]
![screenshot_2015-06-07-21-51-24](https://cloud.githubusercontent.com/assets/348843/8095610/8b988aae-0f84-11e5-88ca-497fb0fb2ac1.png)
