### ISSUE TITLE
"Level" icon displays improperly on "Trends" screen

### ISSUE THREAD

**Issue by johnluetke** [BlueHerons/StatTracker#97]
![227x162 png 52fbe81756584bd68117ba95000372bf](https://cloud.githubusercontent.com/assets/348843/8533978/6816b63c-23ed-11e5-940c-b7587f19cf68.png)

**Comment by ForrestMcIntyre** [comment]
Missing logic at https://github.com/BlueHerons/StatTracker/blob/master/views/trends.twig#L11 for `"level-icon-75"` and `"resistance-agent"`, and `"l16"`, `"l15"`, `"l14"`, etc... classes
